In [19]:
import torch
import numpy as np

In [20]:
a = torch.Tensor(3)
print(a)

tensor([0., 0., 0.])


In [21]:
b = torch.Tensor([1,2])
print(b)

tensor([1., 2.])


In [22]:
c = torch.Tensor([2,2])
print(c)

tensor([2., 2.])


In [23]:
d = torch.rand([2,2,2])
print(d)

tensor([[[0.2219, 0.3330],
         [0.0015, 0.0561]],

        [[0.7023, 0.8941],
         [0.7693, 0.2842]]])


In [24]:
x = torch.randn([3,5])
y = torch.randn([5,4])
z = x @ y
print(z.shape)

torch.Size([3, 4])


In [25]:
z = z+z 

In [26]:
print(z.numpy())
print(type(z)) # torch tensor
print(type(z.numpy())) # numpy array)

[[  1.9752926    5.3772435   -0.19811274   9.7257805 ]
 [  2.930745     2.6033418    1.2908676    1.8914489 ]
 [  5.185331   -11.353455    -1.0462513    3.7863462 ]]
<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [30]:
x = torch.Tensor(np.random.normal([3,5]))
print(type(x)) # torch tensor

<class 'torch.Tensor'>
