In [1]:
import torch
import numpy as np  
import torch.nn.functional as F
print("Using torch", torch.__version__)

Using torch 2.5.0.dev20240702


In [2]:
torch.manual_seed(42)

In [3]:
np_arr = np.array([[1, 2, 3], [4, 5, 6]])
torch_arr = torch.from_numpy(np_arr)
print(torch_arr)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
np_arr = torch_arr.numpy()
print(np_arr)
print(type(np_arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [5]:
x1 = torch.rand(2, 3)
x2 = torch.rand(2, 3)
y = x1 + x2

print("X1", x1)
print("X2", x2)
print("Y", y)

X1 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
X2 tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
Y tensor([[1.1388, 1.7086, 1.3236],
        [1.0925, 1.3250, 1.1945]])


inplace

In [6]:
x2.add_(x1)

tensor([[1.1388, 1.7086, 1.3236],
        [1.0925, 1.3250, 1.1945]])

In [7]:
x = torch.arange(6)
x = x.view(2,3)
print(x)

tensor([[0, 1, 2],
        [3, 4, 5]])


In [8]:
x = x.permute(1,0)
print(x)

tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [10]:
from torchvision.datasets import  FashionMNIST
from torchvision import transforms
import torch.utils.data as data


In [19]:
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.2861,), (0.3530,))
])

trainset = FashionMNIST(root='./data', train=True,
                                        download=True, transform=transform)
trainset, valset = torch.utils.data.random_split(trainset, [50000, 10000])
testset = FashionMNIST(root='./data', train=False,
                                        download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64,
                                          shuffle=True, num_workers=2)
valloader = torch.utils.data.DataLoader(valset, batch_size=64,
                                        shuffle=False, num_workers=2)


testloader = torch.utils.data.DataLoader(testset,
                                         batch_size=64, shuffle=False,
                                         num_workers=2)

In [20]:
imgs, _ = next(iter(trainloader))
print(f"Mean: {imgs.mean().item():5.3f}")
print(f"Standard deviation: {imgs.std().item():5.3f}")
print(f"Maximum: {imgs.max().item():5.3f}")
print(f"Minimum: {imgs.min().item():5.3f}")

Mean: 0.024
Standard deviation: 1.022
Maximum: 2.022
Minimum: -0.810
